language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: 6rkwJDlMWK590zNf0T9BrIIDd/uak1qfyYS9zgqCPcaKTEJjdwuo2IT4aDXRcjlnG5d8EGFyjgfcDtRQ6B0IpHFVwiTRO3uP0y52bGhSZnc5XVrsV0ODRnEQIlEu+xbZh74CCBZ9PTLTMhKxu2h0fhUwnETm2BDl5Tz+4f4JOl0Ecms9WIC6wxTt1uzcfo0x570UljzzjwTa3/yMLOiJHfCboiSd9518bHNMH5ryn79M+kVf1uVBEL8/5WH52e3j/X8tBqhF6NGYIq/xH1VDc/y20WBCJklGqNeIw823sF3fg5LEMDrVfC5acMGZVOzXeiXLaCe20VgpE2XX9Feiwf+ZC9mWciwjenwS8hjgttMAr7vH/ayk12l3ir5/UBnBqQoEdi5RDvdONR/3n2e70TNPmpDTrRuTxCAnhUKdRLkZ0IpkAfAOl/j05dwZ+fASqKvr3jUR+j05V0qyJeCzYZeSuivUPgH5HS76Fc8eIG1hAge2qZKqxPh+k1i36S15mROqw8oH2kI0coyv/s0L5MzVxuMCi7FZ7EReFwrrkKbTz8shADw/5K+vFxE5h+9Al/yOXedqU98OrkH28JB1JCVvUpRdyPAJlXeDEM/D9AtTkRq0t1X0Ojz8x0YJ6f8PWd21oMgrA9/y/s4Nxrh9Y2EbZzY34+Gfzw88SduuMFc=
  app: juskidin-react-api
  on:
    repo: reinhal/juskidin-react-api
